[package]
name = "raftkv"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11"
prost = "0.12"
tokio = { version = "*", features = ["full"] }
tonic-reflection = "0.11.0"
derivative = "2.2.0"
derive-new = "0.6.0"
derive_more = "0.99.17"

[build-dependencies]
tonic-build = "0.11"
